#!/bin/bash
#SBATCH --job-name=Single-Input-BWFILES
# Project:
#SBATCH --account=projectname
# Wall clock limit:
#SBATCH --time=24:00:00
# Max memory usage:
#SBATCH --mem-per-cpu=4G
# Number of cores:
#SBATCH --cpus-per-task=12
#SBATCH --mail-user=email@email.com
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=END

#If you need hugemem...
#--partition=hugemem


## Set up the job environment
source /cluster/bin/jobsetup

module load samtools

set -o errexit

read_path=/work/users/ankushs/foxa1-sumolink/CHIPSEQ/FASTQ-SRA/SINGLE_END
chromsizes=/usit/abel/u1/ankushs/software/FILEFORMATCONVERTER/hg38chromsizes
BamtoBW=/work/users/ankushs/foxa1-sumolink/CHIPSEQ/FASTQ-SRA/BWFILES_RAWBAM


for i in $(ls $read_path/ANALYSIS-INPUTCTRL_CHIPSEQ); do echo

samtools sort -@ 16 $read_path/ANALYSIS-INPUTCTRL_CHIPSEQ/${i}/${i}.bam > $read_path/ANALYSIS-INPUTCTRL_CHIPSEQ/${i}/${i}\_sorted.bam
samtools index -bc $read_path/ANALYSIS-INPUTCTRL_CHIPSEQ/${i}/${i}\_sorted.bam
bamCoverage -b $read_path/ANALYSIS-INPUTCTRL_CHIPSEQ/${i}/${i}\_sorted.bam -o $BamtoBW/SINGLEBW/${i}\_inputctrl.bw

#>$read_path/ANALYSIS-INPUTCTRL_CHIPSEQ/${i}/${i}\_index.bam
done
